"""empty message

Revision ID: 2a4550a3c2f2
Revises: cd2c0a9a869d
Create Date: 2026-02-05 12:35:31.940184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a4550a3c2f2'
down_revision = 'cd2c0a9a869d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regimen_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'regimenes_horarios', ['regimen_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('usuarios_regimen_id_fkey'), type_='foreignkey')
        batch_op.drop_column('rotacion')
        batch_op.drop_column('regimen_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regimen_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rotacion', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('usuarios_regimen_id_fkey'), 'regimenes_horarios', ['regimen_id'], ['id'])

    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('regimen_id')

    # ### end Alembic commands ###
