"""empty message

Revision ID: 509636063d6b
Revises: 38b056be75e1
Create Date: 2025-12-18 22:38:29.715873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509636063d6b'
down_revision = '38b056be75e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vencimiento', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prendas', schema=None) as batch_op:
        batch_op.drop_column('vencimiento')

    # ### end Alembic commands ###
