"""empty message

Revision ID: 5ffd105c2736
Revises: dbf8aa1c2536
Create Date: 2026-02-05 20:29:07.313121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ffd105c2736'
down_revision = 'dbf8aa1c2536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medio_horario', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('medio_horario')

    # ### end Alembic commands ###
