"""empty message

Revision ID: 6ea199d0d465
Revises: 5ffd105c2736
Create Date: 2026-08-05 22:32:33.016494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea199d0d465'
down_revision = '5ffd105c2736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('des_tres_diecisiete', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('des_ciento_once', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('des_cert_prolongada', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('des_preventivo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('des_preventivo')
        batch_op.drop_column('des_cert_prolongada')
        batch_op.drop_column('des_ciento_once')
        batch_op.drop_column('des_tres_diecisiete')

    # ### end Alembic commands ###
