"""empty message

Revision ID: 7669e24a0bca
Revises: 509636063d6b
Create Date: 2025-12-18 22:53:09.597786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7669e24a0bca'
down_revision = '509636063d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prendas', schema=None) as batch_op:
        batch_op.alter_column('talle',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prendas', schema=None) as batch_op:
        batch_op.alter_column('talle',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
