"""empty message

Revision ID: 93a1a2105579
Revises: 7669e24a0bca
Create Date: 2026-01-23 12:17:50.098274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a1a2105579'
down_revision = '7669e24a0bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funcion_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'funcion', ['funcion_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('funcion_id')

    # ### end Alembic commands ###
