"""empty message

Revision ID: a0f2ef428415
Revises: 93a1a2105579
Create Date: 2026-01-25 09:27:39.926474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0f2ef428415'
down_revision = '93a1a2105579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proximo_servicio', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.drop_column('proximo_servicio')

    # ### end Alembic commands ###
