"""empty message

Revision ID: cd2c0a9a869d
Revises: a0f2ef428415
Create Date: 2026-02-01 12:32:16.943295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd2c0a9a869d'
down_revision = 'a0f2ef428415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotacion', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('regimen_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'regimenes_horarios', ['regimen_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('regimen_id')
        batch_op.drop_column('rotacion')

    # ### end Alembic commands ###
