"""empty message

Revision ID: dab433a07061
Revises: 3a2818e62125
Create Date: 2025-11-25 21:45:30.200498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dab433a07061'
down_revision = '3a2818e62125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('licencias_medicas')
    op.drop_table('usuarios_roles_operativos')
    op.drop_table('roles_operativos')
    op.drop_table('licencias_solicitadas')
    op.drop_table('extraordinaria_guardias')
    op.drop_table('solicitudes_cambio')
    op.drop_table('turnos_asignados')
    with op.batch_alter_table('licencias', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('licencias', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    op.create_table('turnos_asignados',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('turno_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos.id'], name='turnos_asignados_turno_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='turnos_asignados_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='turnos_asignados_pkey')
    )
    op.create_table('solicitudes_cambio',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('turno_original_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('turno_solicitado_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usuario_solicitante_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('aprobado_por_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_aprobacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('comentarios', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['aprobado_por_id'], ['usuarios.id'], name='solicitudes_cambio_aprobado_por_id_fkey'),
    sa.ForeignKeyConstraint(['turno_original_id'], ['turnos.id'], name='solicitudes_cambio_turno_original_id_fkey'),
    sa.ForeignKeyConstraint(['turno_solicitado_id'], ['turnos.id'], name='solicitudes_cambio_turno_solicitado_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_solicitante_id'], ['usuarios.id'], name='solicitudes_cambio_usuario_solicitante_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='solicitudes_cambio_pkey')
    )
    op.create_table('extraordinaria_guardias',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('fecha_fin', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('comentario', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='extraordinaria_guardias_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='extraordinaria_guardias_pkey')
    )
    op.create_table('licencias_solicitadas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_inicio', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('fecha_fin', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('motivo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='licencias_solicitadas_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='licencias_solicitadas_pkey')
    )
    op.create_table('roles_operativos',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('roles_operativos_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='roles_operativos_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('usuarios_roles_operativos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rol_operativo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rol_operativo_id'], ['roles_operativos.id'], name='usuarios_roles_operativos_rol_operativo_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='usuarios_roles_operativos_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='usuarios_roles_operativos_pkey')
    )
    op.create_table('licencias_medicas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_inicio', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('fecha_fin', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('motivo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='licencias_medicas_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='licencias_medicas_pkey')
    )
    # ### end Alembic commands ###
